language: c
before_install:
  - sudo apt-get install libev-dev libev4
install:
  - wget https://github.com/hmng/jsonrpc-c/archive/arma_stable.tar.gz 
  - tar xvzf arma_stable.tar.gz
  - cd jsonrpc-c-arma_stable
  - autoreconf -i
  - ./configure --prefix=/usr && make && sudo make install
  - cd ..
compiler:
  - gcc
#  - clang
# Change this to your needs
# script: ./configure && make
script: make
